#! /bin/sh
mLink="${HOME}/.config/quran"
cq="${mLink}/Dr-Mustafa-Khattab_the-Clear-Quran"
cName="${cq}/name"
termL="${mLink}/term"
term="$TERMINAL"

args="$*"

[ -z "$args" ] && printf "Which surah do you wanna read?: " && read -r args

open_surah() {
	less "$cq/$1-no-surah.txt"
}

# dmenu
__dmenu() {
	if [ ! -z "$term" ]
	then

		surah="$([ -z "$1" ] && ls "${cName}" | dmenu -p "Surah : " -l 8)"
		$term -e less "${cName}/${surah}"
	
	elif [ -e "$terml" ]
	then
		term="$(cat "$terml")"
		surah="$([ -z "$1" ] && ls "${cName}" | dmenu -p "Surah : " -l 8)"
		$term -e less "${cName}/${surah}"

	elif [ -z "$term" ] && [ ! -e "$terml" ]
	then
		ter="$(printf "" | dmenu -p "Whats your termnal emulators name?:(give the surah no) ")"
		echo "$ter" > "$termL"
	else
		term="$TERMINAL"	
	fi
}

# fzf search
__fzf() {
	[ -z "$1" ] && fzfName="$( ls "$cName" | fzf )" || fzfName="$( ls "$cName" | fzf -q "$*" )"
	less "${cName}/${fzfName}"

}

# [ "$1" = "d" ] && __dmenu "$2" && exit
# [ -z "$1" ] && [ "$1" != "d" ] && printf "Which surah do you wanna read?:(give the surah no) " && read -r surah

case ${args#[-+]} in
*[!0-9]* | '')
	if [ "$args" = "--dm" ]
	then
		__dmenu
	else
		__fzf "$args"
	fi
	;;

* )
	[ "$args" -le "114" ] && open_surah "$args" || echo "give a valid surah no"
	;;

esac

